### ISSUE TITLE
Erreur de nommage d'un fichier phtml

### ISSUE THREAD

**Issue by jules13470** [nienfba/Ecommerce#1]
Le fichier /www/admin/products/variations/add/addView.phtml renommé en AddView.phtml
Le fichier /www/admin/products/variations/edit/editView.phtml renommé en EditView.phtml

**Comment by nienfba** [comment]
En effet problème de Dev sous Windows, la casse des fichiers n'est pas remontée comme erreur. Le problème va être corrigé !

**Comment by jules13470** [comment]
merci
